export const FETCH_IMAGES = 'FETCH_IMAGES';
export const LOAD_IMAGES = 'LOAD_IMAGES';
export const FETCH_RANDOM = 'FETCH_RANDOM';
export const ADD_IMAGE = 'ADD_IMAGE';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const LOAD_FAVORITES = 'LOAD_FAVORITES';
export const DELETE_IMAGE = 'DELETE_IMAGE';
